# netlify.toml

# Build settings for Netlify
[build]
  # The command to build your site. 
  # This matches the "build" script in your package.json.
  command = "npm run build"

  # The directory that contains the built site.
  # Your vite.config.js specifies 'docs' as the output directory.
  publish = "docs"

  # Optional: Specify the Node.js version to use for the build.
  # This ensures consistency with your local environment (from mise.toml).
  [build.environment]
    NODE_VERSION = "22"

# Redirects and rewrites rules
# This rule is essential for Single Page Applications (SPAs) like React.
# It ensures that all paths are served by index.html, allowing
# client-side routing to handle the navigation.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
